import sys
import string

# Get only the unique names from the generated set
def uniqueNames(filename, original_file):
	unique_names = []
	original_names = []

	with open(original_file) as ogfile:
		for name in ogfile.read().split("\n"):
			original_names.append(name.lower())
		ogfile.close()

	with open(filename) as file:
		for name in file.read().split("\n"):
			if name.strip().lower() not in original_names:
				unique_names.append(name.strip())
		file.close()

	with open(filename, "w+") as file:
		for name in set(unique_names):
			file.write(name.title() + "\n")


# LCS to help find name similiarity
# From https://www.geeksforgeeks.org/longest-common-subsequence/
def lcs(X , Y):
    # find the length of the strings
    m = len(X)
    n = len(Y)

    # declaring the array for storing the dp values
    L = [[None]*(n+1) for i in range(m+1)]

    """Following steps build L[m+1][n+1] in bottom up fashion
    Note: L[i][j] contains length of LCS of X[0..i-1]
    and Y[0..j-1]"""
    for i in range(m+1):
        for j in range(n+1):
            if i == 0 or j == 0 :
                L[i][j] = 0
            elif X[i-1] == Y[j-1]:
                L[i][j] = L[i-1][j-1]+1
            else:
                L[i][j] = max(L[i-1][j] , L[i][j-1])

    # L[m][n] contains the length of LCS of X[0..n-1] & Y[0..m-1]
    return L[m][n]

def name_similarity(filename, original_file, write_name):

	# Read the names into lists
	unique_names = []
	original_names = []

	with open(original_file) as ogfile:
		for name in ogfile.readlines():
			original_names.append(name.strip().lower())
		ogfile.close()

	with open(filename) as file:
		for name in file.readlines():
			unique_names.append(name.strip().lower())
		file.close()

	# Create dict
	name_similarity = {}
	name_subset = {}
	for name in unique_names:
		name_similarity[name] = ""
		name_subset[name] = []

	# Run the LCS algorithm to find the most common name
	for index, name in enumerate(unique_names):
		max_sim = 0
		max_val = ""
		if index % 100 == 0:
			print(index)
		for name2 in original_names:
			sim = lcs(name, name2)
			if sim > max_sim:
				max_sim = sim
				max_val = name2
			if name in name2:
				name_subset[name].append(name2)

		name_similarity[name] = max_val

	# Write the results
	with open(write_name, "w+") as write_file:
		write_file.write("For each new name generated by the network, this files finds\n" + \
		"the most similiar counterpart in the original dataset using the LCS algorithm and\n" + \
		"seeing if the name is a subset of other names.\n")
		write_file.write("New Name: Original Name, [Subset Names]\n")
		for elem in name_similarity:
			write_file.write(string.capwords(elem) + ": " \
				+ string.capwords(name_similarity[elem]) + ', ' \
				+ ', '.join([string.capwords(s) for s in name_subset[name]]) + "\n")


if __name__=="__main__":

	# Get only the unique set of names
	# filename = sys.argv[1]
	# original_file = sys.argv[2]
	# uniqueNames(filename, original_file)

	# Run the name similarity analysis
	new_file = "data/generated_girl_names.txt"
	orig_file = "data/girl_names.txt"
	write_name = "data/girl_names_similarity.txt"
	name_similarity(new_file, orig_file, write_name)

